2025-06-22 15:08:25,291 - qtpyvcp - INFO - Logging to /home/adam/linuxcnc/configs/PrintNC/probe_basic.log
2025-06-22 15:08:25,292 - qtpyvcp - INFO - QtPyVCP Version: 0+unknown
2025-06-22 15:08:25,842 - qtpyvcp.utilities.info - INFO - Machine appearers to be a gantry config having a double Y axis
2025-06-22 15:08:25,843 - qtpyvcp.utilities.info - INFO - The machine has 3 axes and 4 joints
2025-06-22 15:08:25,843 - qtpyvcp.utilities.info - INFO - The Axis/Joint mapping is:
2025-06-22 15:08:25,843 - qtpyvcp.utilities.info - INFO - Axis X --> Joint 0
2025-06-22 15:08:25,843 - qtpyvcp.utilities.info - INFO - Axis Y0 --> Joint 1
2025-06-22 15:08:25,843 - qtpyvcp.utilities.info - INFO - Axis Y1 --> Joint 2
2025-06-22 15:08:25,843 - qtpyvcp.utilities.info - INFO - Axis Z --> Joint 3
2025-06-22 15:08:26,830 - qtpyvcp - INFO - Loading global stylesheet: /usr/lib/python3/dist-packages/probe_basic/probe_basic.qss
2025-06-22 15:08:27,041 - qtpyvcp.hal - INFO - Creating new HAL component: qtpyvcp_manualtoolchange
2025-06-22 15:08:29,265 - qtpyvcp.app.launcher - INFO - Loading POSTGUI_HALFILE: /home/adam/linuxcnc/configs/PrintNC/custom_postgui.hal
2025-06-22 15:08:31,680 - qtpyvcp.widgets.input_widgets.file_system - INFO - File encoding: ascii
2025-06-22 15:08:31,889 - qtpyvcp.widgets.input_widgets.gcode_text_edit - INFO - File encoding: ascii
2025-06-22 15:08:31,903 - qtpyvcp.widgets.display_widgets.vtk_backplot.vtk_backplot - INFO - -------Draw time 0.012835025787353516 seconds ---
2025-06-22 15:08:31,914 - qtpyvcp.app.launcher - CRITICAL - Unhandled exception in vtk_backplot.py line 916
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/qtpyvcp/widgets/display_widgets/vtk_backplot/vtk_backplot.py", line 916, in load_program
    point_01_pos = self.path_offset_start_point[prev_wcs_index]
                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: 8
2025-06-22 15:08:33,040 - qtpyvcp.widgets.input_widgets.gcode_text_edit - INFO - File encoding: ascii
